/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalyzeTab: typeof import('./src/components/DocDetailsTabs/AnalyzeTab.vue')['default']
    ChatAnalysisPanel: typeof import('./src/components/ChatAnalysisPanel.vue')['default']
    ChatDialogs: typeof import('./src/components/ChatDialogs.vue')['default']
    ChatFloating: typeof import('./src/components/ChatFloating.vue')['default']
    ClusterDocumentsList: typeof import('./src/components/ClusterDocumentsList.vue')['default']
    ClusterTab: typeof import('./src/components/DocDetailsTabs/ClusterTab.vue')['default']
    ClusterView: typeof import('./src/components/ClusterView.vue')['default']
    ClusterView_OLD_BACKUP: typeof import('./src/components/ClusterView_OLD_BACKUP.vue')['default']
    ComparisonDialog: typeof import('./src/components/ComparisonDialog.vue')['default']
    DetailsTab: typeof import('./src/components/DocDetailsTabs/DetailsTab.vue')['default']
    DocDetails: typeof import('./src/components/DocDetails.vue')['default']
    DocDetailsPanel: typeof import('./src/components/DocDetailsPanel.vue')['default']
    DocumentMetadataCard: typeof import('./src/components/DocumentMetadataCard.vue')['default']
    DocumentNeighborsView: typeof import('./src/components/DocumentNeighborsView.vue')['default']
    DocumentPreview: typeof import('./src/components/shared/DocumentPreview.vue')['default']
    EmptyState: typeof import('./src/components/shared/EmptyState.vue')['default']
    FooterBar: typeof import('./src/components/FooterBar.vue')['default']
    HeaderBar: typeof import('./src/components/HeaderBar.vue')['default']
    LoadingState: typeof import('./src/components/shared/LoadingState.vue')['default']
    PaginationControls: typeof import('./src/components/PaginationControls.vue')['default']
    PersonsTab: typeof import('./src/components/DocDetailsTabs/PersonsTab.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPanel: typeof import('./src/components/SearchPanel.vue')['default']
    SimilarDocumentsSection: typeof import('./src/components/SimilarDocumentsSection.vue')['default']
    SimilarTab: typeof import('./src/components/DocDetailsTabs/SimilarTab.vue')['default']
    SummaryTab: typeof import('./src/components/DocDetailsTabs/SummaryTab.vue')['default']
    TaskQueue: typeof import('./src/components/TaskQueue.vue')['default']
    UploadPanel: typeof import('./src/components/UploadPanel.vue')['default']
    WritingAssistant: typeof import('./src/components/WritingAssistant.vue')['default']
    WritingTab: typeof import('./src/components/DocDetailsTabs/WritingTab.vue')['default']
  }
}
