# Generated by Django 5.2.7 on 2025-10-27 17:17

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'db_table': 'documents_document_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LegalArea',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Área Legal',
                'verbose_name_plural': 'Áreas Legales',
                'db_table': 'documents_legal_area',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Contenido Completo')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Resumen')),
                ('summary_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('instance', models.CharField(blank=True, help_text='Primera instancia, Segunda instancia, Casación, etc.', max_length=100, null=True, verbose_name='Instancia')),
                ('file_path', models.FileField(upload_to='documentos/', verbose_name='Archivo')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word (DOCX)'), ('doc', 'Word (DOC)'), ('txt', 'Texto plano'), ('other', 'Otro')], default='pdf', max_length=10, verbose_name='Tipo de Archivo')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Tamaño del Archivo (bytes)')),
                ('pages', models.IntegerField(blank=True, null=True, verbose_name='Número de Páginas')),
                ('status', models.CharField(choices=[('uploaded', 'Subido'), ('processing', 'Procesando'), ('processed', 'Procesado'), ('failed', 'Falló')], default='uploaded', max_length=20, verbose_name='Estado')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Procesamiento')),
                ('doc_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documenttype', verbose_name='Tipo de Documento')),
                ('legal_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.legalarea', verbose_name='Área Legal')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documents_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='Nombre de persona o entidad (sin información entre paréntesis)', max_length=255, verbose_name='Nombre Completo')),
                ('normalized_name', models.CharField(db_index=True, help_text='Nombre en mayúsculas sin tildes para búsqueda', max_length=255, verbose_name='Nombre Normalizado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Persona/Entidad',
                'verbose_name_plural': 'Personas/Entidades',
                'db_table': 'documents_person',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['normalized_name'], name='documents_p_normali_8fa582_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentPerson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('demandante', 'Demandante'), ('demandado', 'Demandado'), ('juez', 'Juez'), ('fiscal', 'Fiscal'), ('abogado', 'Abogado'), ('testigo', 'Testigo'), ('perito', 'Perito'), ('tercero', 'Tercero'), ('otro', 'Otro')], max_length=20, verbose_name='Rol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_persons', to='documents.document', verbose_name='Documento')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_documents', to='documents.person', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Persona en Documento',
                'verbose_name_plural': 'Personas en Documentos',
                'db_table': 'documents_document_person',
                'ordering': ['role', 'person__full_name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('chunk_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.IntegerField()),
                ('content', models.TextField()),
                ('content_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
            ],
            options={
                'db_table': 'documents_documentchunk',
                'indexes': [models.Index(fields=['document_id', 'order_number'], name='documents_d_documen_b02739_idx')],
                'unique_together': {('document_id', 'order_number')},
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='documents_d_status_07369e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='documents_d_created_3b0a51_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['instance'], name='documents_d_instanc_8f7071_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['file_type'], name='documents_d_file_ty_1bb410_idx'),
        ),
        migrations.AddIndex(
            model_name='documentperson',
            index=models.Index(fields=['document', 'role'], name='documents_d_documen_44bd29_idx'),
        ),
        migrations.AddIndex(
            model_name='documentperson',
            index=models.Index(fields=['person', 'role'], name='documents_d_person__d9718e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentperson',
            unique_together={('document', 'person', 'role')},
        ),
    ]
