# Generated by Django 5.2.7 on 2025-10-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentperson',
            options={'ordering': ['-is_primary', 'role', 'person__full_name'], 'verbose_name': 'Persona en Documento', 'verbose_name_plural': 'Personas en Documentos'},
        ),
        migrations.AddField(
            model_name='documentperson',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Marca si es demandante/demandado principal', verbose_name='Es Principal'),
        ),
        migrations.AddIndex(
            model_name='documentperson',
            index=models.Index(fields=['is_primary'], name='documents_d_is_prim_5d009a_idx'),
        ),
    ]
