# Generated by Django 5.2.7 on 2025-10-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documentperson_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='case_number',
            field=models.CharField(blank=True, db_index=True, help_text='Número de expediente o caso judicial', max_length=100, null=True, verbose_name='Número de Expediente'),
        ),
    ]
