# Generated by Django 5.2.7 on 2025-10-31 21:55

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_rename_person_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='summary_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='content_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
