# Generated by Django 5.2.7 on 2025-11-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_alter_document_summary_embedding_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="document",
            name="documents_d_instanc_8f7071_idx",
        ),
        migrations.RemoveField(
            model_name="document",
            name="instance",
        ),
        migrations.AddField(
            model_name="document",
            name="jurisdictional_body",
            field=models.CharField(
                blank=True,
                help_text="Órgano jurisdiccional que emite o tramita el documento",
                max_length=255,
                null=True,
                verbose_name="Órgano Jurisdiccional",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="legal_subject",
            field=models.CharField(
                blank=True,
                help_text="Materia específica dentro del área legal (ej: Robo Agravado, Despido Arbitrario, etc.)",
                max_length=255,
                null=True,
                verbose_name="Materia del Área Legal",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["jurisdictional_body"], name="documents_d_jurisdi_a5ccc4_idx"
            ),
        ),
    ]
