# Generated by Django 5.2.7 on 2025-11-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_remove_document_documents_d_instanc_8f7071_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="document_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Fecha de emisión del documento judicial",
                null=True,
                verbose_name="Fecha del Documento",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="issue_place",
            field=models.CharField(
                blank=True,
                help_text="Ciudad o lugar donde se emitió el documento (ej: Lima, Puno, Santa Anita)",
                max_length=200,
                null=True,
                verbose_name="Lugar de Emisión",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="resolution_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Número de resolución judicial (ej: 23-2025, TRES, DOSCIENTOS SETENTA Y NUEVE)",
                max_length=100,
                null=True,
                verbose_name="Número de Resolución",
            ),
        ),
    ]
