# Generated by Django 5.2.7 on 2025-11-05 11:14

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_document_document_date_document_issue_place_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="enhanced_embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=384,
                help_text="Embedding mejorado que combina múltiples campos del documento",
                null=True,
            ),
        ),
    ]
