# Generated by Django 5.2.7 on 2025-11-07 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0009_add_modular_analysis_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTask",
            fields=[
                (
                    "task_id",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID de Tarea Celery",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("upload", "Subida y Extracción"),
                            ("analysis_metadata", "Análisis de Metadatos"),
                            ("analysis_summary", "Análisis de Resumen"),
                            ("analysis_persons", "Análisis de Personas"),
                            ("analysis_full", "Análisis Completo"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Tarea",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("started", "Iniciada"),
                            ("progress", "En Progreso"),
                            ("success", "Completada"),
                            ("failure", "Fallida"),
                            ("revoked", "Cancelada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=5,
                        help_text="1 = Alta prioridad, 10 = Baja prioridad",
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "progress_percent",
                    models.IntegerField(default=0, verbose_name="Progreso (%)"),
                ),
                (
                    "progress_message",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Mensaje de Progreso",
                    ),
                ),
                (
                    "analysis_parts",
                    models.JSONField(
                        blank=True,
                        help_text="Lista de partes: ['metadata', 'summary', 'persons']",
                        null=True,
                        verbose_name="Partes a Analizar",
                    ),
                ),
                (
                    "result",
                    models.JSONField(blank=True, null=True, verbose_name="Resultado"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensaje de Error"
                    ),
                ),
                (
                    "traceback",
                    models.TextField(blank=True, null=True, verbose_name="Traceback"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creada"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Iniciada"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completada"
                    ),
                ),
                (
                    "worker_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Worker"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="documents.document",
                        verbose_name="Documento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarea de Documento",
                "verbose_name_plural": "Tareas de Documentos",
                "db_table": "documents_task",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="documents_t_status_7c9a0d_idx",
                    ),
                    models.Index(
                        fields=["document", "status"],
                        name="documents_t_documen_52e4c0_idx",
                    ),
                    models.Index(
                        fields=["task_type", "status"],
                        name="documents_t_task_ty_b2bff2_idx",
                    ),
                    models.Index(
                        fields=["priority", "status"],
                        name="documents_t_priorit_133861_idx",
                    ),
                ],
            },
        ),
    ]
