# Generated by Django 5.1.4 on 2025-11-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0010_documenttask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documenttask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("upload", "Subida y Extracción"),
                    ("analysis_metadata", "Análisis de Metadatos"),
                    ("analysis_title", "Generación de Título"),
                    ("analysis_summary", "Análisis de Resumen"),
                    ("analysis_persons", "Análisis de Personas"),
                    ("analysis_full", "Análisis Completo"),
                ],
                max_length=50,
                verbose_name="Tipo de Tarea",
            ),
        ),
    ]
