# Generated by Django 5.1.4 on 2025-11-24 17:32

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0012_add_summarizer_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClusterGraph",
            fields=[
                ("graph_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Solo un grafo debe estar activo a la vez",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "document_count",
                    models.IntegerField(
                        help_text="Número de documentos incluidos en este grafo",
                        verbose_name="Cantidad de Documentos",
                    ),
                ),
                (
                    "cluster_count",
                    models.IntegerField(
                        help_text="Número de clusters encontrados (sin contar ruido)",
                        verbose_name="Cantidad de Clusters",
                    ),
                ),
                (
                    "noise_count",
                    models.IntegerField(
                        default=0,
                        help_text="Documentos que no pertenecen a ningún cluster",
                        verbose_name="Documentos de Ruido",
                    ),
                ),
                (
                    "algorithm",
                    models.CharField(
                        default="hdbscan",
                        help_text="Algoritmo de clustering usado (hdbscan, dbscan)",
                        max_length=50,
                        verbose_name="Algoritmo",
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        default="cosine",
                        help_text="Métrica de distancia usada",
                        max_length=50,
                        verbose_name="Métrica",
                    ),
                ),
                (
                    "umap_30d_params",
                    models.JSONField(
                        help_text="Parámetros para reducción 384D → 30D",
                        verbose_name="Parámetros UMAP 30D",
                    ),
                ),
                (
                    "umap_2d_params",
                    models.JSONField(
                        help_text="Parámetros para reducción 30D → 2D (visualización)",
                        verbose_name="Parámetros UMAP 2D",
                    ),
                ),
                (
                    "clustering_params",
                    models.JSONField(
                        help_text="Parámetros del algoritmo de clustering",
                        verbose_name="Parámetros de Clustering",
                    ),
                ),
                (
                    "knn_params",
                    models.JSONField(
                        help_text="Parámetros para construcción del grafo KNN",
                        verbose_name="Parámetros KNN",
                    ),
                ),
                (
                    "computation_time_seconds",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Tiempo de Computación (seg)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grafo de Clusters",
                "verbose_name_plural": "Grafos de Clusters",
                "db_table": "documents_cluster_graph",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "-created_at"],
                        name="documents_c_is_acti_814339_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ClusterGraphNode",
            fields=[
                ("node_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "umap_30d_embedding",
                    pgvector.django.vector.VectorField(
                        dimensions=30,
                        help_text="Embedding reducido para clustering semántico",
                        verbose_name="Embedding UMAP 30D",
                    ),
                ),
                ("x", models.FloatField(verbose_name="Coordenada X (UMAP 2D)")),
                ("y", models.FloatField(verbose_name="Coordenada Y (UMAP 2D)")),
                (
                    "cluster_label",
                    models.IntegerField(
                        help_text="-1 significa ruido (sin cluster)",
                        verbose_name="Label del Cluster",
                    ),
                ),
                (
                    "is_noise",
                    models.BooleanField(
                        default=False,
                        help_text="True si cluster_label == -1",
                        verbose_name="Es Ruido",
                    ),
                ),
                ("doc_title", models.CharField(max_length=255, verbose_name="Título")),
                (
                    "doc_case_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Número de Expediente",
                    ),
                ),
                (
                    "doc_legal_area_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Área Legal"
                    ),
                ),
                (
                    "doc_type_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "doc_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha del Documento"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cluster_nodes",
                        to="documents.document",
                        verbose_name="Documento",
                    ),
                ),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="documents.clustergraph",
                        verbose_name="Grafo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nodo del Grafo",
                "verbose_name_plural": "Nodos del Grafo",
                "db_table": "documents_cluster_graph_node",
                "ordering": ["cluster_label", "document__title"],
            },
        ),
        migrations.CreateModel(
            name="ClusterGraphEdge",
            fields=[
                ("edge_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "similarity",
                    models.FloatField(
                        help_text="Similitud semántica entre los documentos (0-1)",
                        verbose_name="Similitud",
                    ),
                ),
                (
                    "edge_type",
                    models.CharField(
                        default="knn",
                        help_text="knn = K-Nearest Neighbor",
                        max_length=20,
                        verbose_name="Tipo de Arista",
                    ),
                ),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edges",
                        to="documents.clustergraph",
                        verbose_name="Grafo",
                    ),
                ),
                (
                    "source_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="documents.clustergraphnode",
                        verbose_name="Nodo Origen",
                    ),
                ),
                (
                    "target_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="documents.clustergraphnode",
                        verbose_name="Nodo Destino",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arista del Grafo",
                "verbose_name_plural": "Aristas del Grafo",
                "db_table": "documents_cluster_graph_edge",
                "ordering": ["-similarity"],
            },
        ),
        migrations.AddIndex(
            model_name="clustergraphnode",
            index=models.Index(
                fields=["graph", "cluster_label"], name="documents_c_graph_i_fe1aa7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clustergraphnode",
            index=models.Index(
                fields=["graph", "document"], name="documents_c_graph_i_53ff5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clustergraphnode",
            index=models.Index(
                fields=["cluster_label"], name="documents_c_cluster_1a4ab5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="clustergraphnode",
            unique_together={("graph", "document")},
        ),
        migrations.AddIndex(
            model_name="clustergraphedge",
            index=models.Index(
                fields=["graph", "source_node"], name="documents_c_graph_i_16f12f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clustergraphedge",
            index=models.Index(
                fields=["graph", "target_node"], name="documents_c_graph_i_aa8a5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clustergraphedge",
            index=models.Index(
                fields=["-similarity"], name="documents_c_similar_e357af_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="clustergraphedge",
            unique_together={("graph", "source_node", "target_node")},
        ),
    ]
