# Generated by Django 5.1.4 on 2025-11-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0013_clustergraph_clustergraphnode_clustergraphedge_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clustergraph",
            name="calinski_harabasz_score",
            field=models.FloatField(
                blank=True,
                help_text="Ratio de dispersión inter/intra cluster (mayor es mejor)",
                null=True,
                verbose_name="Calinski-Harabasz Score",
            ),
        ),
        migrations.AddField(
            model_name="clustergraph",
            name="davies_bouldin_score",
            field=models.FloatField(
                blank=True,
                help_text="Promedio de similitud entre clusters (menor es mejor)",
                null=True,
                verbose_name="Davies-Bouldin Score",
            ),
        ),
        migrations.AddField(
            model_name="clustergraph",
            name="silhouette_score",
            field=models.FloatField(
                blank=True,
                help_text="Mide cohesión y separación de clusters (-1 a 1, mayor es mejor)",
                null=True,
                verbose_name="Silhouette Score",
            ),
        ),
    ]
