# Generated by Django 5.1.4 on 2025-12-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_add_clean_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='summarizer_type',
            field=models.CharField(choices=[('ollama', 'Ollama (LLM)'), ('ollama_hierarchical', 'Ollama Jerárquico (Documento Completo)'), ('bart', 'BART (Hugging Face)')], default='ollama', help_text='Motor utilizado para generar el resumen del documento', max_length=20, verbose_name='Tipo de Generador de Resumen'),
        ),
        migrations.AlterField(
            model_name='documenttask',
            name='summarizer_type',
            field=models.CharField(blank=True, choices=[('ollama', 'Ollama (LLM)'), ('ollama_hierarchical', 'Ollama Jerárquico (Documento Completo)'), ('bart', 'BART (Hugging Face)')], help_text='Motor a utilizar para generar resumen: ollama o bart', max_length=20, null=True, verbose_name='Tipo de Generador de Resumen'),
        ),
    ]
