# Generated by Django 5.1.4 on 2025-12-18 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_alter_document_summarizer_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BERTopicModel',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_count', models.IntegerField(verbose_name='Número de Documentos')),
                ('topic_count', models.IntegerField(verbose_name='Número de Tópicos')),
                ('outlier_count', models.IntegerField(default=0, help_text='Documentos clasificados como outliers (-1)', verbose_name='Documentos sin Tópico')),
                ('computation_time', models.FloatField(help_text='Segundos que tomó generar el modelo', verbose_name='Tiempo de Computación (s)')),
                ('parameters', models.JSONField(default=dict, help_text='UMAP, HDBSCAN, embedding field, etc.', verbose_name='Parámetros del Modelo')),
                ('is_active', models.BooleanField(default=False, help_text='Solo un modelo puede estar activo a la vez', verbose_name='Modelo Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modelo BERTopic',
                'verbose_name_plural': 'Modelos BERTopic',
                'db_table': 'documents_bertopic_model',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BERTopicTopic',
            fields=[
                ('topic_db_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_id', models.IntegerField(help_text='-1 = outliers/sin tópico', verbose_name='ID del Tópico')),
                ('label', models.CharField(help_text='Label generado desde top keywords', max_length=255, verbose_name='Etiqueta del Tópico')),
                ('keywords', models.JSONField(default=list, help_text='Lista de palabras clave ordenadas por relevancia', verbose_name='Keywords')),
                ('keyword_weights', models.JSONField(default=dict, help_text='Dict {keyword: weight}', verbose_name='Pesos de Keywords')),
                ('document_count', models.IntegerField(help_text='Documentos en este tópico', verbose_name='Número de Documentos')),
                ('is_outlier', models.BooleanField(default=False, help_text='True si topic_id == -1', verbose_name='Es Outlier')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='documents.bertopicmodel', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Tópico BERTopic',
                'verbose_name_plural': 'Tópicos BERTopic',
                'db_table': 'documents_bertopic_topic',
                'ordering': ['topic_id'],
            },
        ),
        migrations.CreateModel(
            name='BERTopicDocument',
            fields=[
                ('bertopic_doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_id_raw', models.IntegerField(help_text='-1 = outlier', verbose_name='Topic ID')),
                ('probability', models.FloatField(help_text='Probabilidad de pertenencia al tópico asignado', null=True, verbose_name='Probabilidad')),
                ('x', models.FloatField(verbose_name='Coordenada X')),
                ('y', models.FloatField(verbose_name='Coordenada Y')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bertopic_assignments', to='documents.document', verbose_name='Documento')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_assignments', to='documents.bertopicmodel', verbose_name='Modelo')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.bertopictopic', verbose_name='Tópico Asignado')),
            ],
            options={
                'verbose_name': 'Documento BERTopic',
                'verbose_name_plural': 'Documentos BERTopic',
                'db_table': 'documents_bertopic_document',
                'ordering': ['topic_id_raw'],
            },
        ),
        migrations.AddIndex(
            model_name='bertopictopic',
            index=models.Index(fields=['model', 'topic_id'], name='documents_b_model_i_5ab9da_idx'),
        ),
        migrations.AddIndex(
            model_name='bertopictopic',
            index=models.Index(fields=['model', '-document_count'], name='documents_b_model_i_b6f543_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bertopictopic',
            unique_together={('model', 'topic_id')},
        ),
        migrations.AddIndex(
            model_name='bertopicdocument',
            index=models.Index(fields=['model', 'topic_id_raw'], name='documents_b_model_i_e9dd5c_idx'),
        ),
        migrations.AddIndex(
            model_name='bertopicdocument',
            index=models.Index(fields=['model', 'document'], name='documents_b_model_i_7101f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bertopicdocument',
            unique_together={('model', 'document')},
        ),
    ]
